server:
  port: 10510
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1233
    username: root
    password: 1qazxsw@
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.chason.nas.bountyhunter.model

